sudo: required
services:
  - docker

before_install:
  - docker build -t cas0559/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cas0559/react-test npm test

after_success:
  - docker build -t cas0559/multi-client ./client
  - docker build -t cas0559/multi-nginx ./nginx
  - docker build -t cas0559/multi-server ./server
  - docker build -t cas0559/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push cas0559/multi-client 
  - docker push cas0559/multi-nginx 
  - docker push cas0559/multi-server 
  - docker push cas0559/multi-worker 
